import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { Provider } from 'react-redux';
import store from "./components/store";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "SalesMap",  // Title for the application
  description: "SalesMap - Dashboard for managing your sales data",
  icons: {
    icon: "/logo.png",  // Path to the logo icon
    apple: "/logo.png",
  }
}
// export const metadata: Metadata = {
//   title: "SalesMap",
//   // description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
    

         <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
            >
          
        {children}
        </ThemeProvider>
           
      </body>
    </html>
  );
}

